
import type { Abbreviation, FlashCard, Inhaler, Injectable, TopDrug } from './types.ts';

export const COMMON_INHALERS: Inhaler[] = [
  { name: 'Select Inhaler...', puffs: 0 },
  { name: 'Advair Diskus 100/50', puffs: 60 },
  { name: 'Advair Diskus 250/50', puffs: 60 },
  { name: 'Advair Diskus 500/50', puffs: 60 },
  { name: 'Advair HFA 45/21', puffs: 120 },
  { name: 'Advair HFA 115/21', puffs: 120 },
  { name: 'Advair HFA 230/21', puffs: 120 },
  { name: 'Albuterol HFA (generic)', puffs: 200 },
  { name: 'ProAir HFA', puffs: 200 },
  { name: 'Proventil HFA', puffs: 200 },
  { name: 'Ventolin HFA', puffs: 200 },
  { name: 'Anoro Ellipta', puffs: 60 },
  { name: 'Breo Ellipta', puffs: 60 },
  { name: 'Combivent Respimat', puffs: 120 },
  { name: 'Dulera 100/5', puffs: 120 },
  { name: 'Dulera 200/5', puffs: 120 },
  { name: 'Flovent Diskus 50', puffs: 60 },
  { name: 'Flovent Diskus 100', puffs: 60 },
  { name: 'Flovent Diskus 250', puffs: 60 },
  { name: 'Flovent HFA 44', puffs: 120 },
  { name: 'Flovent HFA 110', puffs: 120 },
  { name: 'Flovent HFA 220', puffs: 120 },
  { name: 'Incruse Ellipta', puffs: 60 },
  { name: 'QVAR RediHaler 40', puffs: 120 },
  { name: 'QVAR RediHaler 80', puffs: 120 },
  { name: 'Spiriva HandiHaler', puffs: 30 },
  { name: 'Spiriva Respimat', puffs: 60 },
  { name: 'Stiolto Respimat', puffs: 60 },
  { name: 'Symbicort 80/4.5', puffs: 120 },
  { name: 'Symbicort 160/4.5', puffs: 120 },
  { name: 'Trelegy Ellipta', puffs: 60 },
];

export const COMMON_INJECTABLES: Injectable[] = [
  { name: 'Select Injectable...', totalVolume: 0 },
  { name: 'Insulin Vial (e.g., Lantus, Humalog) - 10mL', totalVolume: 10 },
  { name: 'Insulin Pen (e.g., KwikPen, FlexPen) - 3mL', totalVolume: 3 },
  { name: 'Ozempic Pen 2mg/1.5mL (0.25/0.5mg dose)', totalVolume: 1.5 },
  { name: 'Ozempic Pen 4mg/3mL (1mg dose)', totalVolume: 3 },
  { name: 'Ozempic Pen 8mg/3mL (2mg dose)', totalVolume: 3 },
  { name: 'Mounjaro Pen 2.5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Mounjaro Pen 5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Trulicity Pen 0.75mg/0.5mL', totalVolume: 0.5 },
  { name: 'Trulicity Pen 1.5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Wegovy Pen 2.4mg/0.75mL', totalVolume: 0.75 },
  { name: 'Humira Pen 40mg/0.8mL', totalVolume: 0.8 },
  { name: 'Enbrel SureClick 50mg/mL', totalVolume: 1 },
  { name: 'Testosterone Cypionate Vial 200mg/mL - 10mL', totalVolume: 10, defaultDose: 0.5 },
  { name: 'Testosterone Cypionate Vial 200mg/mL - 1mL', totalVolume: 1, defaultDose: 1 },
  { name: 'Lovenox 40mg Syringe', totalVolume: 0.4, defaultDose: 0.4 },
  { name: 'Lovenox 100mg Syringe', totalVolume: 1, defaultDose: 1 },
  { name: 'EpiPen Auto-Injector 0.3mg', totalVolume: 0.3, defaultDose: 0.3 },
  { name: 'Imitrex StatDose 6mg', totalVolume: 0.5, defaultDose: 0.5 },
  { name: 'Prolia Syringe 60mg/mL', totalVolume: 1, defaultDose: 1 },
];

export const COMMON_ABBREVIATIONS: Abbreviation[] = [
  { term: 'ac', definition: 'before meals' },
  { term: 'pc', definition: 'after meals' },
  { term: 'bid', definition: 'twice a day' },
  { term: 'tid', definition: 'three times a day' },
  { term: 'qid', definition: 'four times a day' },
  { term: 'qhs', definition: 'at bedtime' },
  { term: 'prn', definition: 'as needed' },
  { term: 'po', definition: 'by mouth' },
  { term: 'sl', definition: 'sublingual (under the tongue)' },
  { term: 'IM', definition: 'intramuscular' },
  { term: 'IV', definition: 'intravenous' },
  { term: 'SubQ', definition: 'subcutaneous' },
  { term: 'gtt', definition: 'drop' },
  { term: 'od', definition: 'right eye' },
  { term: 'os', definition: 'left eye' },
  { term: 'ou', definition: 'both eyes' },
  { term: 'ad', definition: 'right ear' },
  { term: 'as', definition: 'left ear' },
  { term: 'au', definition: 'both ears' },
  { term: 'Rx', definition: 'prescription' },
  { term: 'Sig', definition: 'directions for use' },
  { term: 'disp', definition: 'dispense' },
  { term: 'NPO', definition: 'nothing by mouth' },
  { term: 'stat', definition: 'immediately' },
];

export const TOP_DRUGS_LIST: TopDrug[] = [
  { brand: "Abilify", generic: "Aripiprazole" },
  { brand: "Adderall", generic: "Amphetamine/Dextroamphetamine" },
  { brand: "Advair Diskus", generic: "Fluticasone/Salmeterol" },
  { brand: "Advil", generic: "Ibuprofen" },
  { brand: "Aldactone", generic: "Spironolactone" },
  { brand: "Aleve", generic: "Naproxen" },
  { brand: "Allegra", generic: "Fexofenadine" },
  { brand: "Altace", generic: "Ramipril" },
  { brand: "Amaryl", generic: "Glimepiride" },
  { brand: "Ambien", generic: "Zolpidem" },
  { brand: "Amitiza", generic: "Lubiprostone" },
  { brand: "Amoxil", generic: "Amoxicillin" },
  { brand: "AndroGel", generic: "Testosterone" },
  { brand: "Anoro Ellipta", generic: "Umeclidinium/Vilanterol" },
  { brand: "Aranesp", generic: "Darbepoetin Alfa" },
  { brand: "Arixtra", generic: "Fondaparinux" },
  { brand: "Armour Thyroid", generic: "Thyroid" },
  { brand: "Asacol", generic: "Mesalamine" },
  { brand: "Aspirin", generic: "Aspirin" },
  { brand: "Ativan", generic: "Lorazepam" },
  { brand: "Augmentin", generic: "Amoxicillin/Clavulanate" },
  { brand: "Avelox", generic: "Moxifloxacin" },
  { brand: "Avodart", generic: "Dutasteride" },
  { brand: "Bactrim", generic: "Sulfamethoxazole/Trimethoprim" },
  { brand: "Bactroban", generic: "Mupirocin" },
  { brand: "Benicar", generic: "Olmesartan" },
  { brand: "Bentyl", generic: "Dicyclomine" },
  { brand: "Betapace", generic: "Sotalol" },
  { brand: "Biaxin", generic: "Clarithromycin" },
  { brand: "Boniva", generic: "Ibandronate" },
  { brand: "Breo Ellipta", generic: "Fluticasone/Vilanterol" },
  { brand: "Brilinta", generic: "Ticagrelor" },
  { brand: "Bystolic", generic: "Nebivolol" },
  { brand: "Calan", generic: "Verapamil" },
  { brand: "Cardizem", generic: "Diltiazem" },
  { brand: "Cardura", generic: "Doxazosin" },
  { brand: "Catapres", generic: "Clonidine" },
  { brand: "Celebrex", generic: "Celecoxib" },
  { brand: "Celexa", generic: "Citalopram" },
  { brand: "Chantix", generic: "Varenicline" },
  { brand: "Cialis", generic: "Tadalafil" },
  { brand: "Cipro", generic: "Ciprofloxacin" },
  { brand: "Claritin", generic: "Loratadine" },
  { brand: "Cleocin", generic: "Clindamycin" },
  { brand: "Clobex", generic: "Clobetasol" },
  { brand: "Klonopin", generic: "Clonazepam" },
  { brand: "Clozaril", generic: "Clozapine" },
  { brand: "Colcrys", generic: "Colchicine" },
  { brand: "Combivent Respimat", generic: "Ipratropium/Albuterol" },
  { brand: "Concerta", generic: "Methylphenidate" },
  { brand: "Coreg", generic: "Carvedilol" },
  { brand: "Coumadin", generic: "Warfarin" },
  { brand: "Cozaar", generic: "Losartan" },
  { brand: "Crestor", generic: "Rosuvastatin" },
  { brand: "Cymbalta", generic: "Duloxetine" },
  { brand: "Deltasone", generic: "Prednisone" },
  { brand: "Depakote", generic: "Divalproex" },
  { brand: "Desyrel", generic: "Trazodone" },
  { brand: "Detrol", generic: "Tolterodine" },
  { brand: "Dexilant", generic: "Dexlansoprazole" },
  { brand: "Diflucan", generic: "Fluconazole" },
  { brand: "Dilantin", generic: "Phenytoin" },
  { brand: "Diovan", generic: "Valsartan" },
  { brand: "Ditropan", generic: "Oxybutynin" },
  { brand: "Duragesic", generic: "Fentanyl" },
  { brand: "Dyazide", generic: "Triamterene/HCTZ" },
  { brand: "Effexor", generic: "Venlafaxine" },
  { brand: "Elavil", generic: "Amitriptyline" },
  { brand: "Eliquis", generic: "Apixaban" },
  { brand: "Enablex", generic: "Darifenacin" },
  { brand: "Enbrel", generic: "Etanercept" },
  { brand: "Evista", generic: "Raloxifene" },
  { brand: "Exelon", generic: "Rivastigmine" },
  { brand: "Exforge", generic: "Amlodipine/Valsartan" },
  { brand: "Famvir", generic: "Famciclovir" },
  { brand: "Femara", generic: "Letrozole" },
  { brand: "Fioricet", generic: "Butalbital/Acetaminophen/Caffeine" },
  { brand: "Flagyl", generic: "Metronidazole" },
  { brand: "Flexeril", generic: "Cyclobenzaprine" },
  { brand: "Flomax", generic: "Tamsulosin" },
  { brand: "Flonase", generic: "Fluticasone" },
  { brand: "Focalin", generic: "Dexmethylphenidate" },
  { brand: "Folic Acid", generic: "Folic Acid" },
  { brand: "Foradil", generic: "Formoterol" },
  { brand: "Fosamax", generic: "Alendronate" },
  { brand: "Geodon", generic: "Ziprasidone" },
  { brand: "Gleevec", generic: "Imatinib" },
  { brand: "Glucophage", generic: "Metformin" },
  { brand: "Glucotrol", generic: "Glipizide" },
  { brand: "Haldol", generic: "Haloperidol" },
  { brand: "Humalog", generic: "Insulin Lispro" },
  { brand: "Humira", generic: "Adalimumab" },
  { brand: "HCTZ", generic: "Hydrochlorothiazide" },
  { brand: "Hytrin", generic: "Terazosin" },
  { brand: "Hyzaar", generic: "Losartan/HCTZ" },
  { brand: "Imitrex", generic: "Sumatriptan" },
  { brand: "Imuran", generic: "Azathioprine" },
  { brand: "Inderal", generic: "Propranolol" },
  { brand: "Invega", generic: "Paliperidone" },
  { brand: "Invokana", generic: "Canagliflozin" },
  { brand: "Januvia", generic: "Sitagliptin" },
  { brand: "Jardiance", generic: "Empagliflozin" },
  { brand: "Jentadueto", generic: "Linagliptin/Metformin" },
  { brand: "Keppra", generic: "Levetiracetam" },
  { brand: "Lamictal", generic: "Lamotrigine" },
  { brand: "Lanoxin", generic: "Digoxin" },
  { brand: "Lantus", generic: "Insulin Glargine" },
  { brand: "Lasix", generic: "Furosemide" },
  { brand: "Latuda", generic: "Lurasidone" },
  { brand: "Levaquin", generic: "Levofloxacin" },
  { brand: "Levemir", generic: "Insulin Detemir" },
  { brand: "Lexapro", generic: "Escitalopram" },
  { brand: "Librium", generic: "Chlordiazepoxide" },
  { brand: "Lidoderm", generic: "Lidocaine" },
  { brand: "Linzess", generic: "Linaclotide" },
  { brand: "Lipitor", generic: "Atorvastatin" },
  { brand: "Lithobid", generic: "Lithium" },
  { brand: "Lopid", generic: "Gemfibrozil" },
  { brand: "Lopressor", generic: "Metoprolol" },
  { brand: "Lotrel", generic: "Amlodipine/Benazepril" },
  { brand: "Lovaza", generic: "Omega-3-Acid Ethyl Esters" },
  { brand: "Lovenox", generic: "Enoxaparin" },
  { brand: "Lumigan", generic: "Bimatoprost" },
  { brand: "Lunesta", generic: "Eszopiclone" },
  { brand: "Lupron", generic: "Leuprolide" },
  { brand: "Lyrica", generic: "Pregabalin" },
  { brand: "Macrobid", generic: "Nitrofurantoin" },
  { brand: "Maxalt", generic: "Rizatriptan" },
  { brand: "Medrol", generic: "Methylprednisolone" },
  { brand: "Mevacor", generic: "Lovastatin" },
  { brand: "Mobic", generic: "Meloxicam" },
  { brand: "Motrin", generic: "Ibuprofen" },
  { brand: "Mounjaro", generic: "Tirzepatide" },
  { brand: "Namenda", generic: "Memantine" },
  { brand: "Naprosyn", generic: "Naproxen" },
  { brand: "Nasonex", generic: "Mometasone" },
  { brand: "Neurontin", generic: "Gabapentin" },
  { brand: "Nexium", generic: "Esomeprazole" },
  { brand: "Niaspan", generic: "Niacin" },
  { brand: "Norco", generic: "Hydrocodone/Acetaminophen" },
  { brand: "Norvasc", generic: "Amlodipine" },
  { brand: "Novolog", generic: "Insulin Aspart" },
  { brand: "Nucynta", generic: "Tapentadol" },
  { brand: "Omnicef", generic: "Cefdinir" },
  { brand: "Onglyza", generic: "Saxagliptin" },
  { brand: "Oxycontin", generic: "Oxycodone" },
  { brand: "Ozempic", generic: "Semaglutide" },
  { brand: "Paxil", generic: "Paroxetine" },
  { brand: "Pepcid", generic: "Famotidine" },
  { brand: "Percocet", generic: "Oxycodone/Acetaminophen" },
  { brand: "Plavix", generic: "Clopidogrel" },
  { brand: "Pradaxa", generic: "Dabigatran" },
  { brand: "Pravachol", generic: "Pravastatin" },
  { brand: "Premarin", generic: "Conjugated Estrogens" },
  { brand: "Prevacid", generic: "Lansoprazole" },
  { brand: "Prilosec", generic: "Omeprazole" },
  { brand: "Pristiq", generic: "Desvenlafaxine" },
  { brand: "ProAir HFA", generic: "Albuterol" },
  { brand: "Procardia", generic: "Nifedipine" },
  { brand: "Prograf", generic: "Tacrolimus" },
  { brand: "Prolia", generic: "Denosumab" },
  { brand: "Prometrium", generic: "Progesterone" },
  { brand: "Proscar", generic: "Finasteride" },
  { brand: "Protonix", generic: "Pantoprazole" },
  { brand: "Proventil", generic: "Albuterol" },
  { brand: "Provigil", generic: "Modafinil" },
  { brand: "Prozac", generic: "Fluoxetine" },
  { brand: "Pulmicort", generic: "Budesonide" },
  { brand: "Pyridium", generic: "Phenazopyridine" },
  { brand: "QVAR", generic: "Beclomethasone" },
  { brand: "Remicade", generic: "Infliximab" },
  { brand: "Remeron", generic: "Mirtazapine" },
  { brand: "Requip", generic: "Ropinirole" },
  { brand: "Restasis", generic: "Cyclosporine" },
  { brand: "Restoril", generic: "Temazepam" },
  { brand: "Risperdal", generic: "Risperidone" },
  { brand: "Ritalin", generic: "Methylphenidate" },
  { brand: "Robaxin", generic: "Methocarbamol" },
  { brand: "Seroquel", generic: "Quetiapine" },
  { brand: "Singulair", generic: "Montelukast" },
  { brand: "Skelaxin", generic: "Metaxalone" },
  { brand: "Soma", generic: "Carisoprodol" },
  { brand: "Spiriva", generic: "Tiotropium" },
  { brand: "Stelara", generic: "Ustekinumab" },
  { brand: "Strattera", generic: "Atomoxetine" },
  { brand: "Suboxone", generic: "Buprenorphine/Naloxone" },
  { brand: "Synthroid", generic: "Levothyroxine" },
  { brand: "Tamiflu", generic: "Oseltamivir" },
  { brand: "Tegretol", generic: "Carbamazepine" },
  { brand: "Tekturna", generic: "Aliskiren" },
  { brand: "Tenormin", generic: "Atenolol" },
  { brand: "Tessalon", generic: "Benzonatate" },
  { brand: "Topamax", generic: "Topiramate" },
  { brand: "Toprol-XL", generic: "Metoprolol Succinate" },
  { brand: "Toradol", generic: "Ketorolac" },
  { brand: "Tradjenta", generic: "Linagliptin" },
  { brand: "Tramadol", generic: "Tramadol" },
  { brand: "Tricor", generic: "Fenofibrate" },
  { brand: "Trileptal", generic: "Oxcarbazepine" },
  { brand: "Trulicity", generic: "Dulaglutide" },
  { brand: "Tylenol", generic: "Acetaminophen" },
  { brand: "Ultram", generic: "Tramadol" },
  { brand: "Uloric", generic: "Febuxostat" },
  { brand: "Valium", generic: "Diazepam" },
  { brand: "Valtrex", generic: "Valacyclovir" },
  { brand: "Vancocin", generic: "Vancomycin" },
  { brand: "Vasotec", generic: "Enalapril" },
  { brand: "Ventolin", generic: "Albuterol" },
  { brand: "Vesicare", generic: "Solifenacin" },
  { brand: "Viagra", generic: "Sildenafil" },
  { brand: "Vibramycin", generic: "Doxycycline" },
  { brand: "Vicodin", generic: "Hydrocodone/Acetaminophen" },
  { brand: "Victoza", generic: "Liraglutide" },
  { brand: "Vistaril", generic: "Hydroxyzine" },
  { brand: "Vitamin D", generic: "Ergocalciferol/Cholecalciferol" },
  { brand: "Vivelle-Dot", generic: "Estradiol" },
  { brand: "Vyvanse", generic: "Lisdexamfetamine" },
  { brand: "Wellbutrin", generic: "Bupropion" },
  { brand: "Xalatan", generic: "Latanoprost" },
  { brand: "Xanax", generic: "Alprazolam" },
  { brand: "Xarelto", generic: "Rivaroxaban" },
  { brand: "Xeloda", generic: "Capecitabine" },
  { brand: "Xenical", generic: "Orlistat" },
  { brand: "Xgeva", generic: "Denosumab" },
  { brand: "Xifaxan", generic: "Rifaximin" },
  { brand: "Xolair", generic: "Omalizumab" },
  { brand: "Xopenex", generic: "Levalbuterol" },
  { brand: "Xtandi", generic: "Enzalutamide" },
  { brand: "Yasmin", generic: "Drospirenone/Ethinyl Estradiol" },
  { brand: "Zanaflex", generic: "Tizanidine" },
  { brand: "Zantac", generic: "Ranitidine" },
  { brand: "Zestril", generic: "Lisinopril" },
  { brand: "Zetia", generic: "Ezetimibe" },
  { brand: "Ziac", generic: "Bisoprolol/HCTZ" },
  { brand: "Zithromax", generic: "Azithromycin" },
  { brand: "Zocor", generic: "Simvastatin" },
  { brand: "Zofran", generic: "Ondansetron" },
  { brand: "Zoloft", generic: "Sertraline" },
  { brand: "Zomig", generic: "Zolmitriptan" },
  { brand: "Zovirax", generic: "Acyclovir" },
  { brand: "Zyprexa", generic: "Olanzapine" },
  { brand: "Zyrtec", generic: "Cetirizine" },
  { brand: "Zyvox", generic: "Linezolid" },
];

export const PTCB_FLASHCARDS: FlashCard[] = [
  // Top 200 Drugs
  { category: "Top 200 Drugs", question: "What is the brand name for Sertraline?", answer: "Zoloft" },
  { category: "Top 200 Drugs", question: "What is the therapeutic class for Metformin?", answer: "Biguanide (Antidiabetic)" },
  { category: "Top 200 Drugs", question: "What is the generic name for Lipitor?", answer: "Atorvastatin" },
  { category: "Top 200 Drugs", question: "Lisinopril belongs to which drug class?", answer: "ACE Inhibitor" },
  { category: "Top 200 Drugs", question: "What is the generic name for Xanax?", answer: "Alprazolam" },
  { category: "Top 200 Drugs", question: "What is the brand name for Omeprazole?", answer: "Prilosec" },
  { category: "Top 200 Drugs", question: "What is the generic name for Synthroid?", answer: "Levothyroxine" },
  { category: "Top 200 Drugs", question: "What is the brand name for Fluoxetine?", answer: "Prozac" },
  { category: "Top 200 Drugs", question: "What is the generic name for Norvasc?", answer: "Amlodipine" },
  { category: "Top 200 Drugs", question: "What drug class does Metoprolol belong to?", answer: "Beta Blocker" },
  { category: "Top 200 Drugs", question: "What is the brand name for Warfarin?", answer: "Coumadin" },
  { category: "Top 200 Drugs", question: "What is the generic name for Lexapro?", answer: "Escitalopram" },
  { category: "Top 200 Drugs", question: "What is the brand name for Hydrochlorothiazide?", answer: "HCTZ (also Microzide)" },
  { category: "Top 200 Drugs", question: "What drug class does Simvastatin belong to?", answer: "Statin (HMG-CoA Reductase Inhibitor)" },
  { category: "Top 200 Drugs", question: "What is the generic name for Plavix?", answer: "Clopidogrel" },
  { category: "Top 200 Drugs", question: "What is the brand name for Gabapentin?", answer: "Neurontin" },
  { category: "Top 200 Drugs", question: "What is the generic name for Advair?", answer: "Fluticasone/Salmeterol" },
  { category: "Top 200 Drugs", question: "What drug class does Losartan belong to?", answer: "ARB (Angiotensin Receptor Blocker)" },
  { category: "Top 200 Drugs", question: "What is the brand name for Tramadol?", answer: "Ultram" },
  { category: "Top 200 Drugs", question: "What is the generic name for Vicodin?", answer: "Hydrocodone/Acetaminophen" },

  // Pharmacy Law
  { category: "Pharmacy Law", question: "Which DEA form is used to order Schedule II controlled substances?", answer: "DEA Form 222" },
  { category: "Pharmacy Law", question: "Which law requires pharmacists to offer counseling to Medicaid patients?", answer: "OBRA '90 (Omnibus Budget Reconciliation Act of 1990)" },
  { category: "Pharmacy Law", question: "What does the abbreviation HIPAA stand for?", answer: "Health Insurance Portability and Accountability Act" },
  { category: "Pharmacy Law", question: "Which DEA form is used to report the theft or significant loss of controlled substances?", answer: "DEA Form 106" },
  { category: "Pharmacy Law", question: "How many years can a DEA registration be valid for?", answer: "3 years" },
  { category: "Pharmacy Law", question: "What is the maximum number of refills allowed for Schedule III-IV controlled substances?", answer: "5 refills" },
  { category: "Pharmacy Law", question: "How long is a Schedule II prescription valid?", answer: "90 days from the date written" },
  { category: "Pharmacy Law", question: "What does DAW stand for?", answer: "Dispense As Written" },
  { category: "Pharmacy Law", question: "Which schedule has the highest abuse potential?", answer: "Schedule I" },
  { category: "Pharmacy Law", question: "How often must controlled substance inventories be taken?", answer: "Every 2 years (biannually)" },
  { category: "Pharmacy Law", question: "What is the Poison Prevention Packaging Act?", answer: "Requires child-resistant packaging for most medications" },
  { category: "Pharmacy Law", question: "How long must prescription records be kept?", answer: "At least 2 years" },
  { category: "Pharmacy Law", question: "What is the Orange Book used for?", answer: "FDA publication listing approved drug products with therapeutic equivalence evaluations" },
  { category: "Pharmacy Law", question: "What does NDC stand for?", answer: "National Drug Code" },

  // Calculations
  { category: "Calculations", question: "A prescription calls for 30mg of a drug, but it is only available as a 120mg/4mL solution. How many mL are needed?", answer: "1 mL" },
  { category: "Calculations", question: "How many grams of dextrose are in 500mL of D5W (Dextrose 5% in Water)?", answer: "25 grams" },
  { category: "Calculations", question: "Convert 150 pounds to kilograms. (1 kg = 2.2 lbs)", answer: "Approximately 68.2 kg" },
  { category: "Calculations", question: "A patient takes 2 tablets twice daily of a medication. How many tablets are needed for a 30-day supply?", answer: "120 tablets" },
  { category: "Calculations", question: "If an insurance copay is $15 and the patient pays $35 total, what is the insurance portion?", answer: "$20" },
  { category: "Calculations", question: "How many milliliters are in 2 teaspoons?", answer: "10 mL (1 tsp = 5 mL)" },
  { category: "Calculations", question: "A 70kg patient needs 5mg/kg/day of a medication. What is the total daily dose?", answer: "350 mg" },
  { category: "Calculations", question: "If a bottle contains 100 tablets and the patient takes 1.5 tablets daily, how many days will it last?", answer: "Approximately 67 days" },
  { category: "Calculations", question: "Convert 2.5 grams to milligrams.", answer: "2,500 mg" },
  { category: "Calculations", question: "A prescription is for 240mL with directions to take 5mL three times daily. How many days will this last?", answer: "16 days" },

  // Terminology
  { category: "Terminology", question: "What does the sig code 'qhs' mean?", answer: "At bedtime" },
  { category: "Terminology", question: "What does 'po' stand for?", answer: "By mouth" },
  { category: "Terminology", question: "What does 'prn' mean?", answer: "As needed" },
  { category: "Terminology", question: "What does 'bid' mean?", answer: "Twice a day" },
  { category: "Terminology", question: "What does 'tid' mean?", answer: "Three times a day" },
  { category: "Terminology", question: "What does 'qid' mean?", answer: "Four times a day" },
  { category: "Terminology", question: "What does 'ac' mean?", answer: "Before meals" },
  { category: "Terminology", question: "What does 'pc' mean?", answer: "After meals" },
  { category: "Terminology", question: "What does 'NPO' mean?", answer: "Nothing by mouth" },
  { category: "Terminology", question: "What does 'stat' mean?", answer: "Immediately" },
  { category: "Terminology", question: "What does 'SubQ' mean?", answer: "Subcutaneous" },
  { category: "Terminology", question: "What does 'IM' mean?", answer: "Intramuscular" },
  { category: "Terminology", question: "What does 'IV' mean?", answer: "Intravenous" },
  { category: "Terminology", question: "What does 'gtt' mean?", answer: "Drop" },

  // Safety
  { category: "Safety", question: "Name a pair of common look-alike/sound-alike drugs.", answer: "Celebrex (celecoxib) and Celexa (citalopram)" },
  { category: "Safety", question: "What are the high-alert medication categories?", answer: "Insulin, anticoagulants, chemotherapy, opioids" },
  { category: "Safety", question: "What color is used for chemotherapy warning labels?", answer: "Purple" },
  { category: "Safety", question: "What does a black box warning indicate?", answer: "Serious or life-threatening risks" },
  { category: "Safety", question: "What is the proper storage temperature for most refrigerated medications?", answer: "36-46°F (2-8°C)" },
  { category: "Safety", question: "Name another pair of look-alike/sound-alike drugs.", answer: "Hydralazine and Hydroxyzine" },
  { category: "Safety", question: "What does MedWatch report?", answer: "Adverse drug events and medical device problems to the FDA" },
  { category: "Safety", question: "What is the purpose of tall man lettering?", answer: "To distinguish look-alike drug names (e.g., DOPamine vs DOBUTamine)" },

  // Hospital Pharmacy
  { category: "Hospital Pharmacy", question: "What is a TPN?", answer: "Total Parenteral Nutrition, an IV solution providing nutrients to patients who cannot eat." },
  { category: "Hospital Pharmacy", question: "What does 'unit dose' mean?", answer: "Individual doses packaged for single administration" },
  { category: "Hospital Pharmacy", question: "What is an IV piggyback (IVPB)?", answer: "A small volume IV medication infused through an existing IV line" },
  { category: "Hospital Pharmacy", question: "What is the difference between stock and non-stock medications?", answer: "Stock medications are kept in inventory; non-stock are ordered as needed" },
  { category: "Hospital Pharmacy", question: "What is a code cart?", answer: "Emergency medication cart for cardiac arrest situations" },
  { category: "Hospital Pharmacy", question: "What does 'IV push' mean?", answer: "Medication injected directly into an IV line over a short period" },

  // Insurance & Billing
  { category: "Insurance", question: "What does AWP stand for?", answer: "Average Wholesale Price" },
  { category: "Insurance", question: "What is a prior authorization?", answer: "Insurance approval required before dispensing certain medications" },
  { category: "Insurance", question: "What does MAC pricing mean?", answer: "Maximum Allowable Cost - the maximum amount insurance will pay for a generic drug" },
  { category: "Insurance", question: "What is a deductible?", answer: "The amount a patient must pay before insurance coverage begins" },
  { category: "Insurance", question: "What does 'days supply' refer to?", answer: "The number of days a dispensed quantity of medication will last" },
  { category: "Insurance", question: "What is a formulary?", answer: "A list of medications covered by an insurance plan" },

  // Compounding
  { category: "Compounding", question: "What is an ointment?", answer: "A semisolid preparation in an oleaginous (greasy) base" },
  { category: "Compounding", question: "What is a cream?", answer: "A semisolid preparation in a water-removable base" },
  { category: "Compounding", question: "What does 'q.s.' mean in compounding?", answer: "Quantity sufficient (add enough to make)" },
  { category: "Compounding", question: "What is a capsule machine used for?", answer: "Filling empty capsule shells with powder medications" },
  { category: "Compounding", question: "What is trituration?", answer: "The process of reducing particle size by grinding in a mortar and pestle" },

  // Inventory Management
  { category: "Inventory", question: "What does 'FIFO' stand for?", answer: "First In, First Out - inventory rotation method" },
  { category: "Inventory", question: "What is an NDC number?", answer: "National Drug Code - unique identifier for drug products" },
  { category: "Inventory", question: "What does 'back order' mean?", answer: "Medication temporarily unavailable from the manufacturer" },
  { category: "Inventory", question: "What is a recall?", answer: "Removal of a product from the market due to safety concerns" },
  { category: "Inventory", question: "What are the three types of drug recalls?", answer: "Class I (dangerous), Class II (temporary health problems), Class III (unlikely to cause harm)" }
];