
import type { Abbreviation, FlashCard, Inhaler, Injectable, TopDrug } from './types.ts';

export const COMMON_INHALERS: Inhaler[] = [
  { name: 'Select Inhaler...', puffs: 0 },
  { name: 'Advair Diskus 100/50', puffs: 60 },
  { name: 'Advair Diskus 250/50', puffs: 60 },
  { name: 'Advair Diskus 500/50', puffs: 60 },
  { name: 'Advair HFA 45/21', puffs: 120 },
  { name: 'Advair HFA 115/21', puffs: 120 },
  { name: 'Advair HFA 230/21', puffs: 120 },
  { name: 'Albuterol HFA (generic)', puffs: 200 },
  { name: 'ProAir HFA', puffs: 200 },
  { name: 'Proventil HFA', puffs: 200 },
  { name: 'Ventolin HFA', puffs: 200 },
  { name: 'Anoro Ellipta', puffs: 60 },
  { name: 'Breo Ellipta', puffs: 60 },
  { name: 'Combivent Respimat', puffs: 120 },
  { name: 'Dulera 100/5', puffs: 120 },
  { name: 'Dulera 200/5', puffs: 120 },
  { name: 'Flovent Diskus 50', puffs: 60 },
  { name: 'Flovent Diskus 100', puffs: 60 },
  { name: 'Flovent Diskus 250', puffs: 60 },
  { name: 'Flovent HFA 44', puffs: 120 },
  { name: 'Flovent HFA 110', puffs: 120 },
  { name: 'Flovent HFA 220', puffs: 120 },
  { name: 'Incruse Ellipta', puffs: 60 },
  { name: 'QVAR RediHaler 40', puffs: 120 },
  { name: 'QVAR RediHaler 80', puffs: 120 },
  { name: 'Spiriva HandiHaler', puffs: 30 },
  { name: 'Spiriva Respimat', puffs: 60 },
  { name: 'Stiolto Respimat', puffs: 60 },
  { name: 'Symbicort 80/4.5', puffs: 120 },
  { name: 'Symbicort 160/4.5', puffs: 120 },
  { name: 'Trelegy Ellipta', puffs: 60 },
];

export const COMMON_INJECTABLES: Injectable[] = [
  { name: 'Select Injectable...', totalVolume: 0 },
  { name: 'Insulin Vial (e.g., Lantus, Humalog) - 10mL', totalVolume: 10 },
  { name: 'Insulin Pen (e.g., KwikPen, FlexPen) - 3mL', totalVolume: 3 },
  { name: 'Ozempic Pen 2mg/1.5mL (0.25/0.5mg dose)', totalVolume: 1.5 },
  { name: 'Ozempic Pen 4mg/3mL (1mg dose)', totalVolume: 3 },
  { name: 'Ozempic Pen 8mg/3mL (2mg dose)', totalVolume: 3 },
  { name: 'Mounjaro Pen 2.5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Mounjaro Pen 5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Trulicity Pen 0.75mg/0.5mL', totalVolume: 0.5 },
  { name: 'Trulicity Pen 1.5mg/0.5mL', totalVolume: 0.5 },
  { name: 'Wegovy Pen 2.4mg/0.75mL', totalVolume: 0.75 },
  { name: 'Humira Pen 40mg/0.8mL', totalVolume: 0.8 },
  { name: 'Enbrel SureClick 50mg/mL', totalVolume: 1 },
  { name: 'Testosterone Cypionate Vial 200mg/mL - 10mL', totalVolume: 10, defaultDose: 0.5 },
  { name: 'Testosterone Cypionate Vial 200mg/mL - 1mL', totalVolume: 1, defaultDose: 1 },
  { name: 'Lovenox 40mg Syringe', totalVolume: 0.4, defaultDose: 0.4 },
  { name: 'Lovenox 100mg Syringe', totalVolume: 1, defaultDose: 1 },
  { name: 'EpiPen Auto-Injector 0.3mg', totalVolume: 0.3, defaultDose: 0.3 },
  { name: 'Imitrex StatDose 6mg', totalVolume: 0.5, defaultDose: 0.5 },
  { name: 'Prolia Syringe 60mg/mL', totalVolume: 1, defaultDose: 1 },
];

export const COMMON_ABBREVIATIONS: Abbreviation[] = [
  { term: 'ac', definition: 'before meals' },
  { term: 'pc', definition: 'after meals' },
  { term: 'bid', definition: 'twice a day' },
  { term: 'tid', definition: 'three times a day' },
  { term: 'qid', definition: 'four times a day' },
  { term: 'qhs', definition: 'at bedtime' },
  { term: 'prn', definition: 'as needed' },
  { term: 'po', definition: 'by mouth' },
  { term: 'sl', definition: 'sublingual (under the tongue)' },
  { term: 'IM', definition: 'intramuscular' },
  { term: 'IV', definition: 'intravenous' },
  { term: 'SubQ', definition: 'subcutaneous' },
  { term: 'gtt', definition: 'drop' },
  { term: 'od', definition: 'right eye' },
  { term: 'os', definition: 'left eye' },
  { term: 'ou', definition: 'both eyes' },
  { term: 'ad', definition: 'right ear' },
  { term: 'as', definition: 'left ear' },
  { term: 'au', definition: 'both ears' },
  { term: 'Rx', definition: 'prescription' },
  { term: 'Sig', definition: 'directions for use' },
  { term: 'disp', definition: 'dispense' },
  { term: 'NPO', definition: 'nothing by mouth' },
  { term: 'stat', definition: 'immediately' },
];

export const TOP_DRUGS_LIST: TopDrug[] = [
  { brand: "Abilify", generic: "Aripiprazole" },
  { brand: "Adderall", generic: "Amphetamine/Dextroamphetamine" },
  { brand: "Advair Diskus", generic: "Fluticasone/Salmeterol" },
  { brand: "Advil", generic: "Ibuprofen" },
  { brand: "Aldactone", generic: "Spironolactone" },
  { brand: "Aleve", generic: "Naproxen" },
  { brand: "Allegra", generic: "Fexofenadine" },
  { brand: "Altace", generic: "Ramipril" },
  { brand: "Amaryl", generic: "Glimepiride" },
  { brand: "Ambien", generic: "Zolpidem" },
  { brand: "Amitiza", generic: "Lubiprostone" },
  { brand: "Amoxil", generic: "Amoxicillin" },
  { brand: "AndroGel", generic: "Testosterone" },
  { brand: "Anoro Ellipta", generic: "Umeclidinium/Vilanterol" },
  { brand: "Aranesp", generic: "Darbepoetin Alfa" },
  { brand: "Arixtra", generic: "Fondaparinux" },
  { brand: "Armour Thyroid", generic: "Thyroid" },
  { brand: "Asacol", generic: "Mesalamine" },
  { brand: "Aspirin", generic: "Aspirin" },
  { brand: "Ativan", generic: "Lorazepam" },
  { brand: "Augmentin", generic: "Amoxicillin/Clavulanate" },
  { brand: "Avelox", generic: "Moxifloxacin" },
  { brand: "Avodart", generic: "Dutasteride" },
  { brand: "Bactrim", generic: "Sulfamethoxazole/Trimethoprim" },
  { brand: "Bactroban", generic: "Mupirocin" },
  { brand: "Benicar", generic: "Olmesartan" },
  { brand: "Bentyl", generic: "Dicyclomine" },
  { brand: "Betapace", generic: "Sotalol" },
  { brand: "Biaxin", generic: "Clarithromycin" },
  { brand: "Boniva", generic: "Ibandronate" },
  { brand: "Breo Ellipta", generic: "Fluticasone/Vilanterol" },
  { brand: "Brilinta", generic: "Ticagrelor" },
  { brand: "Bystolic", generic: "Nebivolol" },
  { brand: "Calan", generic: "Verapamil" },
  { brand: "Cardizem", generic: "Diltiazem" },
  { brand: "Cardura", generic: "Doxazosin" },
  { brand: "Catapres", generic: "Clonidine" },
  { brand: "Celebrex", generic: "Celecoxib" },
  { brand: "Celexa", generic: "Citalopram" },
  { brand: "Chantix", generic: "Varenicline" },
  { brand: "Cialis", generic: "Tadalafil" },
  { brand: "Cipro", generic: "Ciprofloxacin" },
  { brand: "Claritin", generic: "Loratadine" },
  { brand: "Cleocin", generic: "Clindamycin" },
  { brand: "Clobex", generic: "Clobetasol" },
  { brand: "Klonopin", generic: "Clonazepam" },
  { brand: "Clozaril", generic: "Clozapine" },
  { brand: "Colcrys", generic: "Colchicine" },
  { brand: "Combivent Respimat", generic: "Ipratropium/Albuterol" },
  { brand: "Concerta", generic: "Methylphenidate" },
  { brand: "Coreg", generic: "Carvedilol" },
  { brand: "Coumadin", generic: "Warfarin" },
  { brand: "Cozaar", generic: "Losartan" },
  { brand: "Crestor", generic: "Rosuvastatin" },
  { brand: "Cymbalta", generic: "Duloxetine" },
  { brand: "Deltasone", generic: "Prednisone" },
  { brand: "Depakote", generic: "Divalproex" },
  { brand: "Desyrel", generic: "Trazodone" },
  { brand: "Detrol", generic: "Tolterodine" },
  { brand: "Dexilant", generic: "Dexlansoprazole" },
  { brand: "Diflucan", generic: "Fluconazole" },
  { brand: "Dilantin", generic: "Phenytoin" },
  { brand: "Diovan", generic: "Valsartan" },
  { brand: "Ditropan", generic: "Oxybutynin" },
  { brand: "Duragesic", generic: "Fentanyl" },
  { brand: "Dyazide", generic: "Triamterene/HCTZ" },
  { brand: "Effexor", generic: "Venlafaxine" },
  { brand: "Elavil", generic: "Amitriptyline" },
  { brand: "Eliquis", generic: "Apixaban" },
  { brand: "Enablex", generic: "Darifenacin" },
  { brand: "Enbrel", generic: "Etanercept" },
  { brand: "Evista", generic: "Raloxifene" },
  { brand: "Exelon", generic: "Rivastigmine" },
  { brand: "Exforge", generic: "Amlodipine/Valsartan" },
  { brand: "Famvir", generic: "Famciclovir" },
  { brand: "Femara", generic: "Letrozole" },
  { brand: "Fioricet", generic: "Butalbital/Acetaminophen/Caffeine" },
  { brand: "Flagyl", generic: "Metronidazole" },
  { brand: "Flexeril", generic: "Cyclobenzaprine" },
  { brand: "Flomax", generic: "Tamsulosin" },
  { brand: "Flonase", generic: "Fluticasone" },
  { brand: "Focalin", generic: "Dexmethylphenidate" },
  { brand: "Folic Acid", generic: "Folic Acid" },
  { brand: "Foradil", generic: "Formoterol" },
  { brand: "Fosamax", generic: "Alendronate" },
  { brand: "Geodon", generic: "Ziprasidone" },
  { brand: "Gleevec", generic: "Imatinib" },
  { brand: "Glucophage", generic: "Metformin" },
  { brand: "Glucotrol", generic: "Glipizide" },
  { brand: "Haldol", generic: "Haloperidol" },
  { brand: "Humalog", generic: "Insulin Lispro" },
  { brand: "Humira", generic: "Adalimumab" },
  { brand: "HCTZ", generic: "Hydrochlorothiazide" },
  { brand: "Hytrin", generic: "Terazosin" },
  { brand: "Hyzaar", generic: "Losartan/HCTZ" },
  { brand: "Imitrex", generic: "Sumatriptan" },
  { brand: "Imuran", generic: "Azathioprine" },
  { brand: "Inderal", generic: "Propranolol" },
  { brand: "Invega", generic: "Paliperidone" },
  { brand: "Invokana", generic: "Canagliflozin" },
  { brand: "Januvia", generic: "Sitagliptin" },
  { brand: "Jardiance", generic: "Empagliflozin" },
  { brand: "Jentadueto", generic: "Linagliptin/Metformin" },
  { brand: "Keppra", generic: "Levetiracetam" },
  { brand: "Lamictal", generic: "Lamotrigine" },
  { brand: "Lanoxin", generic: "Digoxin" },
  { brand: "Lantus", generic: "Insulin Glargine" },
  { brand: "Lasix", generic: "Furosemide" },
  { brand: "Latuda", generic: "Lurasidone" },
  { brand: "Levaquin", generic: "Levofloxacin" },
  { brand: "Levemir", generic: "Insulin Detemir" },
  { brand: "Lexapro", generic: "Escitalopram" },
  { brand: "Librium", generic: "Chlordiazepoxide" },
  { brand: "Lidoderm", generic: "Lidocaine" },
  { brand: "Linzess", generic: "Linaclotide" },
  { brand: "Lipitor", generic: "Atorvastatin" },
  { brand: "Lithobid", generic: "Lithium" },
  { brand: "Lopid", generic: "Gemfibrozil" },
  { brand: "Lopressor", generic: "Metoprolol" },
  { brand: "Lotrel", generic: "Amlodipine/Benazepril" },
  { brand: "Lovaza", generic: "Omega-3-Acid Ethyl Esters" },
  { brand: "Lovenox", generic: "Enoxaparin" },
  { brand: "Lumigan", generic: "Bimatoprost" },
  { brand: "Lunesta", generic: "Eszopiclone" },
  { brand: "Lupron", generic: "Leuprolide" },
  { brand: "Lyrica", generic: "Pregabalin" },
  { brand: "Macrobid", generic: "Nitrofurantoin" },
  { brand: "Maxalt", generic: "Rizatriptan" },
  { brand: "Medrol", generic: "Methylprednisolone" },
  { brand: "Mevacor", generic: "Lovastatin" },
  { brand: "Mobic", generic: "Meloxicam" },
  { brand: "Motrin", generic: "Ibuprofen" },
  { brand: "Mounjaro", generic: "Tirzepatide" },
  { brand: "Namenda", generic: "Memantine" },
  { brand: "Naprosyn", generic: "Naproxen" },
  { brand: "Nasonex", generic: "Mometasone" },
  { brand: "Neurontin", generic: "Gabapentin" },
  { brand: "Nexium", generic: "Esomeprazole" },
  { brand: "Niaspan", generic: "Niacin" },
  { brand: "Norco", generic: "Hydrocodone/Acetaminophen" },
  { brand: "Norvasc", generic: "Amlodipine" },
  { brand: "Novolog", generic: "Insulin Aspart" },
  { brand: "Nucynta", generic: "Tapentadol" },
  { brand: "Omnicef", generic: "Cefdinir" },
  { brand: "Onglyza", generic: "Saxagliptin" },
  { brand: "Oxycontin", generic: "Oxycodone" },
  { brand: "Ozempic", generic: "Semaglutide" },
  { brand: "Paxil", generic: "Paroxetine" },
  { brand: "Pepcid", generic: "Famotidine" },
  { brand: "Percocet", generic: "Oxycodone/Acetaminophen" },
  { brand: "Plavix", generic: "Clopidogrel" },
  { brand: "Pradaxa", generic: "Dabigatran" },
  { brand: "Pravachol", generic: "Pravastatin" },
  { brand: "Premarin", generic: "Conjugated Estrogens" },
  { brand: "Prevacid", generic: "Lansoprazole" },
  { brand: "Prilosec", generic: "Omeprazole" },
  { brand: "Pristiq", generic: "Desvenlafaxine" },
  { brand: "ProAir HFA", generic: "Albuterol" },
  { brand: "Procardia", generic: "Nifedipine" },
  { brand: "Prograf", generic: "Tacrolimus" },
  { brand: "Prolia", generic: "Denosumab" },
  { brand: "Prometrium", generic: "Progesterone" },
  { brand: "Proscar", generic: "Finasteride" },
  { brand: "Protonix", generic: "Pantoprazole" },
  { brand: "Proventil", generic: "Albuterol" },
  { brand: "Provigil", generic: "Modafinil" },
  { brand: "Prozac", generic: "Fluoxetine" },
  { brand: "Pulmicort", generic: "Budesonide" },
  { brand: "Pyridium", generic: "Phenazopyridine" },
  { brand: "QVAR", generic: "Beclomethasone" },
  { brand: "Remicade", generic: "Infliximab" },
  { brand: "Remeron", generic: "Mirtazapine" },
  { brand: "Requip", generic: "Ropinirole" },
  { brand: "Restasis", generic: "Cyclosporine" },
  { brand: "Restoril", generic: "Temazepam" },
  { brand: "Risperdal", generic: "Risperidone" },
  { brand: "Ritalin", generic: "Methylphenidate" },
  { brand: "Robaxin", generic: "Methocarbamol" },
  { brand: "Seroquel", generic: "Quetiapine" },
  { brand: "Singulair", generic: "Montelukast" },
  { brand: "Skelaxin", generic: "Metaxalone" },
  { brand: "Soma", generic: "Carisoprodol" },
  { brand: "Spiriva", generic: "Tiotropium" },
  { brand: "Stelara", generic: "Ustekinumab" },
  { brand: "Strattera", generic: "Atomoxetine" },
  { brand: "Suboxone", generic: "Buprenorphine/Naloxone" },
  { brand: "Synthroid", generic: "Levothyroxine" },
  { brand: "Tamiflu", generic: "Oseltamivir" },
  { brand: "Tegretol", generic: "Carbamazepine" },
  { brand: "Tekturna", generic: "Aliskiren" },
  { brand: "Tenormin", generic: "Atenolol" },
  { brand: "Tessalon", generic: "Benzonatate" },
  { brand: "Topamax", generic: "Topiramate" },
  { brand: "Toprol-XL", generic: "Metoprolol Succinate" },
  { brand: "Toradol", generic: "Ketorolac" },
  { brand: "Tradjenta", generic: "Linagliptin" },
  { brand: "Tramadol", generic: "Tramadol" },
  { brand: "Tricor", generic: "Fenofibrate" },
  { brand: "Trileptal", generic: "Oxcarbazepine" },
  { brand: "Trulicity", generic: "Dulaglutide" },
  { brand: "Tylenol", generic: "Acetaminophen" },
  { brand: "Ultram", generic: "Tramadol" },
  { brand: "Uloric", generic: "Febuxostat" },
  { brand: "Valium", generic: "Diazepam" },
  { brand: "Valtrex", generic: "Valacyclovir" },
  { brand: "Vancocin", generic: "Vancomycin" },
  { brand: "Vasotec", generic: "Enalapril" },
  { brand: "Ventolin", generic: "Albuterol" },
  { brand: "Vesicare", generic: "Solifenacin" },
  { brand: "Viagra", generic: "Sildenafil" },
  { brand: "Vibramycin", generic: "Doxycycline" },
  { brand: "Vicodin", generic: "Hydrocodone/Acetaminophen" },
  { brand: "Victoza", generic: "Liraglutide" },
  { brand: "Vistaril", generic: "Hydroxyzine" },
  { brand: "Vitamin D", generic: "Ergocalciferol/Cholecalciferol" },
  { brand: "Vivelle-Dot", generic: "Estradiol" },
  { brand: "Vyvanse", generic: "Lisdexamfetamine" },
  { brand: "Wellbutrin", generic: "Bupropion" },
  { brand: "Xalatan", generic: "Latanoprost" },
  { brand: "Xanax", generic: "Alprazolam" },
  { brand: "Xarelto", generic: "Rivaroxaban" },
  { brand: "Xeloda", generic: "Capecitabine" },
  { brand: "Xenical", generic: "Orlistat" },
  { brand: "Xgeva", generic: "Denosumab" },
  { brand: "Xifaxan", generic: "Rifaximin" },
  { brand: "Xolair", generic: "Omalizumab" },
  { brand: "Xopenex", generic: "Levalbuterol" },
  { brand: "Xtandi", generic: "Enzalutamide" },
  { brand: "Yasmin", generic: "Drospirenone/Ethinyl Estradiol" },
  { brand: "Zanaflex", generic: "Tizanidine" },
  { brand: "Zantac", generic: "Ranitidine" },
  { brand: "Zestril", generic: "Lisinopril" },
  { brand: "Zetia", generic: "Ezetimibe" },
  { brand: "Ziac", generic: "Bisoprolol/HCTZ" },
  { brand: "Zithromax", generic: "Azithromycin" },
  { brand: "Zocor", generic: "Simvastatin" },
  { brand: "Zofran", generic: "Ondansetron" },
  { brand: "Zoloft", generic: "Sertraline" },
  { brand: "Zomig", generic: "Zolmitriptan" },
  { brand: "Zovirax", generic: "Acyclovir" },
  { brand: "Zyprexa", generic: "Olanzapine" },
  { brand: "Zyrtec", generic: "Cetirizine" },
  { brand: "Zyvox", generic: "Linezolid" },
];

export const PTCB_FLASHCARDS: FlashCard[] = [
  { category: "Top 200 Drugs", question: "What is the brand name for Sertraline?", answer: "Zoloft" },
  { category: "Top 200 Drugs", question: "What is the therapeutic class for Metformin?", answer: "Biguanide (Antidiabetic)" },
  { category: "Top 200 Drugs", question: "What is the generic name for Lipitor?", answer: "Atorvastatin" },
  { category: "Top 200 Drugs", question: "Lisinopril belongs to which drug class?", answer: "ACE Inhibitor" },
  { category: "Pharmacy Law", question: "Which DEA form is used to order Schedule II controlled substances?", answer: "DEA Form 222" },
  { category: "Pharmacy Law", question: "Which law requires pharmacists to offer counseling to Medicaid patients?", answer: "OBRA '90 (Omnibus Budget Reconciliation Act of 1990)" },
  { category: "Pharmacy Law", question: "What does the abbreviation HIPAA stand for?", answer: "Health Insurance Portability and Accountability Act" },
  { category: "Calculations", question: "A prescription calls for 30mg of a drug, but it is only available as a 120mg/4mL solution. How many mL are needed?", answer: "1 mL" },
  { category: "Calculations", question: "How many grams of dextrose are in 500mL of D5W (Dextrose 5% in Water)?", answer: "25 grams" },
  { category: "Terminology", question: "What does the sig code 'qhs' mean?", answer: "At bedtime" },
  { category: "Terminology", question: "What does 'po' stand for?", answer: "By mouth" },
  { category: "Safety", question: "Name a pair of common look-alike/sound-alike drugs.", answer: "Celebrex (celecoxib) and Celexa (citalopram) / hydralazine and hydroxyzine" },
  { category: "Hospital Pharmacy", question: "What is a TPN?", answer: "Total Parenteral Nutrition, an IV solution providing nutrients to patients who cannot eat." },
  { category: "Community Pharmacy", question: "How long is a prescription for a non-controlled substance valid?", answer: "Typically one year from the date it was written." },
  { category: "Calculations", question: "Convert 150 pounds to kilograms. (1 kg = 2.2 lbs)", answer: "Approximately 68.2 kg" },
  { category: "Top 200 Drugs", question: "What is the generic name for Xanax?", answer: "Alprazolam" },
  { category: "Pharmacy Law", question: "Which DEA form is used to report the theft or significant loss of controlled substances?", answer: "DEA Form 106" },
];